development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: loveydovy_development
  pool: 5
  username: root
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: loveydovy_test
  pool: 5
  username: root
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: loveydovy_production
  pool: 5
  username: root
  host: localhost